esphome:
  name: esp-one
  friendly_name: esp-one

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: VERBOSE
  baud_rate: 115200
  deassert_rts_dtr: true

# Enable Home Assistant API
api:
  encryption:
    key: "s6dwdqx6fpiGNJa/IFBUYepPJ7K/YHhmUX/SixPtTPI="

ota:
  - platform: esphome
    password: "ed8591bc22bb5ee5a519da8e38e1dfbf"

time:
  - platform: homeassistant
    id: homeassistant_time

switch:
  - platform: gpio
    pin:
      number: 2
      mode: output
    id: internalLED

  - platform: homeassistant
    id: nevera
    entity_id: switch.nevera_enchufe_1
    internal: true
    on_turn_on:
      - homeassistant.action:
          action: notify.persistent_notification
          data:
            message: Nevera encendida
    on_turn_off:
      - homeassistant.action:
          action: notify.persistent_notification
          data:
            message: Nevera apagada


# light.wiz_rgbw_tunable_0e3ab0
 

# Example configuration entry
font:
  - file: 'fonts/slkscr.ttf'
    id: font1
    size: 8

  - file: 'fonts/BebasNeue-Regular.ttf'
    id: font2
    size: 48

  - file: 'fonts/arial.ttf'
    id: font3
    size: 14

wifi:
  id: wifiHome
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
    - ssid: !secret wifi_ssid_EXT
      password: !secret wifi_password_EXT

# Optional manual IP
  manual_ip:
    static_ip: 192.168.0.28
    gateway: 192.168.0.1
    subnet: 255.255.254.0

  on_connect:
    - switch.toggle: internalLED
    - delay: 5s  # Gives time for improv results to be transmitted
    - logger.log: "Connected!"
    - delay: 5s  # Gives time for improv results to be transmitted
    - switch.turn_off: internalLED
    - homeassistant.action:
        action: notify.persistent_notification
        data:
          message: Connected to Wifi 😊
  on_disconnect:
    - switch.turn_off: internalLED
    - logger.log: "Not connected"
    - homeassistant.action:
        action: notify.persistent_notification
        data:
          message: Not connected to Wifi 😣
  
  # # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-One Fallback Hotspot"
    password: !secret wifi_password

captive_portal:

sensor:
  - platform: homeassistant
    id: humedad
    entity_id: sensor.sensor_humedad
    unit_of_measurement: "%"
    device_class: "humidity"
    state_class: "measurement"
    internal: true
    on_value_range:
      - above: 60.0
        then:
          - homeassistant.action: 
              action: notify.persistent_notification
              data_template:
                message: >
                  {{ states('sensor.sensor_humedad', with_unit=True) }}
          - switch.turn_on: internalLED
      - below: 60.0
        then: 
          - homeassistant.action: 
              action: notify.persistent_notification
              data:
                message: Humedad por debajo del 60%
          - switch.turn_off: internalLED
    # filters:
    #   - heartbeat: 300s

  - platform: homeassistant
    id: temperatura
    entity_id: sensor.sensor_temperatura
    unit_of_measurement: "ºC"
    device_class: "temperature"
    state_class: "measurement"
    internal: true
    # filters:
    #   - heartbeat: 300s

  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s

  - platform: homeassistant
    id: voltaje
    entity_id: sensor.nevera_voltaje
    unit_of_measurement: "V"
    internal: true

i2c:
  sda: GPIO21
  scl: GPIO22

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    id: pantalla
    lambda: |-
      if(id(wifiHome).is_connected()){
        it.printf(127, 0, id(font1), TextAlign::TOP_RIGHT, "conectado");
        it.strftime(0, 60, id(font2), TextAlign::BASELINE_LEFT, "%H:%M", id(homeassistant_time).now());
        if (id(temperatura).has_state()) {
          it.printf(127, 23, id(font3), TextAlign::TOP_RIGHT , "%.1f°", id(temperatura).state);
        }
        if (id(humedad).has_state()) {
          it.printf(127, 60, id(font3), TextAlign::BASELINE_RIGHT , "%.1f%%", id(humedad).state);
        }
        if (id(nevera).state) {
          it.print(0, 0, id(font3), "ON");
        } else {
          it.print(0, 0, id(font3), "OFF");
        }
        if (id(detector).state) {
          it.print(32, 0, id(font3), "YES");
        } 
      }
      else {
        it.printf(64, 0, id(font1), TextAlign::TOP_CENTER, "NO conectado");
      }
    # update_interval: 30s

binary_sensor:
  - platform: gpio
    pin: GPIO16
    id: detector
    name: "PIR Sensor"
    device_class: motion
    on_state:
      then:
        - if:
            condition:
              binary_sensor.is_on: detector
            then:
              - homeassistant.service:
                  service: light.turn_on
                  data:
                    entity_id: light.wiz_rgbw_tunable_0dbb7e
                    color_name: "blue"
                    brightness_pct: "70"
              - delay: 5min      
            else:
              - homeassistant.service:
                  service: light.turn_off
                  data:
                    entity_id: light.wiz_rgbw_tunable_0dbb7e